COOKING_TIME_MIN = 1
COOKING_TIME_MAX = 32000

AMOUNT_INGREDIENT_MIN = 1
AMOUNT_INGREDIENT_MAX = 32000

FONT_SIZE_DEF = 14
FONT_SIZE_CART = 24

Y_POSITION_PARAM = 50

Y_POSITION_INGR = 800
X_POSITION_INGR = 50

INDENT = 20

Y_POSITION_CART = 15

ERROR_MSG = "Ошибка авторизации"
